apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: alb-ingress-controller
  name: alb-ingress-controller
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alb-ingress-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alb-ingress-controller
    spec:
      containers:
        - name: alb-ingress-controller
          args:
            - --ingress-class=alb
            # - --cluster-name=devCluster
            - --aws-vpc-id=vpc-0a4b83de3703f0ac6
            - --aws-region=us-east-1

          image: docker.io/amazon/aws-alb-ingress-controller:v2.6.2 

      serviceAccountName: alb-ingress-controller
